
[information]
 name = 'tailscheme'
 background = 'dark'
 author = 'Alejandro Camara <hi@alejandrocamara.info>'

[palette]
  fg = '#F8FAFC'
  bg = '#1E293B'
  dark = '#0F172A'
  white = '#F8FAFC'
  comment = '#64748b'
  gray_light = '#CBD5E1'
  gray = '#94A3B8'
  blue_bg = '#0c4a6e'
  blue = '#7DD3FC'
  green = '#5EEAD4'
  cyan = '#67E8F9'
  light_red = '#FECDD3'
  red = '#fda4af'
  orange = '#FDBA74'
  yellow = '#FDE047'
  purple = '#A78BFA'
  magenta = '#F472B6'
  cursor_fg = '#F8FAFC'
  cursor_bg = '#0F172A'
  sign_add = '#10B981'
  sign_change = '#3B82F6'
  sign_delete = '#EF4444'
  tree_sign_add = '#22C55E'
  tree_sign_change = '#EAB308'
  error_red = '#EF4444'
  warning_orange = '#F97316'
  info_yellow = '#FACC15'
  hint_blue = '#0EA5E9'
  success_green = '#22C55e'

[s]
 Normal = 'fg bg'
 SignColumn = '- bg'
 MsgArea = 'fg dark'
 ModeMsg = 'fg bg'
 MsgSeparator = 'fg bg'
 SpellBad = 'light_red - u'
 SpellCap = 'yellow - u'
 SpellLocal = 'green - u'
 SpellRare = 'purple - u'
 NormalNC = 'fg bg'
 Pmenu = 'gray_light dark - - 50'
 PmenuSel = 'bg blue'
 WildMenu = 'bg blue'
 CursorLineNr = 'gray_light - b'
 Comment = 'comment - i'
 Folded = 'gray bg'
 FoldColumn = 'dark bg'
 LineNr = 'gray -'
 FloatBorder = 'fg dark'
 Whitespace = 'bg -'
 VertSplit = 'gray bg'
 CursorLine = '- dark'
 CursorColumn = '- dark'
 ColorColumn = '- bg'
 NormalFloat = '- dark'
 Visual = 'dark blue'
 VisualNOS = '- bg'
 WarningMsg = 'error_red bg'
 DiffAdd = 'bg sign_add'
 DiffChange = 'bg sign_change u'
 DiffDelete = 'bg sign_delete'
 QuickFixLine = 'dark blue'
 PmenuSbar = '- dark'
 PmenuThumb = '- gray'
 MatchWord = '- - u'
 MatchParen = 'hint_blue bg u'
 MatchWordCur = '- - u'
 MatchParenCur = '- - u'
 Cursor = 'cursor_fg cursor_bg'
 lCursor = 'cursor_fg cursor_bg'
 CursorIM = 'cursor_fg cursor_bg'
 TermCursor = 'cursor_fg cursor_bg'
 TermCursorNC = 'cursor_fg cursor_bg'
 Conceal = 'gray'
 Directory = 'blue'
 SpecialKey = 'blue - b'
 Title = 'blue - b'
 ErrorMsg = 'error_red bg b'
 Search = 'dark green'
 IncSearch = 'dark green'
 Substitute = 'dark blue'
 MoreMsg = 'green'
 Question = 'orange'
 EndOfBuffer = 'bg'
 NonText = 'bg'
 Variable = 'blue'
 String = 'white'
 Character = 'white'
 Constant = 'blue'
 Number = 'white'
 Boolean = 'blue'
 Float = 'white'
 Identifier = 'white'
 Function = 'magenta'
 Operator = 'gray'
 Type = 'cyan'
 StorageClass = 'blue'
 Structure = 'blue'
 Typedef = 'blue'
 Keyword = 'gray'
 Statement = 'magenta'
 Conditional = 'blue'
 Repeat = 'magenta'
 Label = 'magenta'
 Exception = 'purple'
 Include = 'magenta'
 PreProc = 'magenta'
 Define = 'magenta'
 Macro = 'magenta'
 PreCondit = 'magenta'
 Special = 'blue'
 SpecialChar = 'white'
 Tag = 'magenta'
 Debug = 'red'
 Delimiter = 'gray -'
 SpecialComment = 'comment'
 Underlined = '- - u'
 Bold = '- - b'
 Italic = '- - i'
 Ignore = 'cyan bg b'
 Todo = 'green dark b'
 Error = 'error_red dark b'
 TabLine = 'gray_light gray_light'
 TabLineSel = 'white gray_light'
 TabLineFill = 'gray_light gray_light'

[Treesitter]
 TSComment = 'link:Comment'
 TSAnnotation = 'blue'
 TSAttribute = 'cyan'
 TSConstructor = 'magenta'
 TSType = 'cyan'
 TSTypeBuiltin = 'white'
 TSConditional = 'gray'
 TSException = 'magenta'
 TSInclude = 'gray'
 TSKeywordReturn = 'gray_light'
 TSKeyword = 'gray'
 TSKeywordFunction = 'gray_light'
 TSLabel = 'blue'
 TSNamespace = 'cyan'
 TSRepeat = 'gray_light'
 TSConstant = 'white'
 TSConstBuiltin = 'white'
 TSFloat = 'white'
 TSNumber = 'white'
 TSBoolean = 'white'
 TSCharacter = 'white'
 TSError = 'error_red'
 TSFunction = 'magenta'
 TSFuncBuiltin = 'blue'
 TSMethod = 'magenta'
 TSConstMacro = 'magenta'
 TSFuncMacro = 'blue'
 TSVariable = 'magenta'
 TSVariableBuiltin = 'white'
 TSProperty = 'white'
 TSField = 'fg'
 TSParameter = 'white'
 TSParameterReference = 'purple'
 TSSymbol = 'blue'
 TSText = 'fg'
 TSOperator = 'gray'
 TSPunctDelimiter = 'fg -'
 TSTagDelimiter = 'gray'
 TSTagAttribute = 'gray_light'
 TSPunctBracket = 'gray -'
 TSPunctSpecial = 'purple'
 TSString = 'blue'
 TSStringRegex = 'blue'
 TSStringEscape = 'blue'
 TSTag = 'magenta'
 TSEmphasis = '- - i'
 TSUnderline = '- - u'
 TSTitle = 'fg - -'
 TSLiteral = 'white'
 TSURI = 'blue - u'
 TSKeywordOperator = 'purple'
 TSStructure = 'blue'
 TSStrong = 'blue - b'
 TSQueryLinterError = 'warning_orange'
 TreesitterContext = '- dark'

[Git]
 SignAdd = 'sign_add'
 SignChange = 'sign_change'
 SignDelete = 'sign_delete'
 GitSignsAdd = 'sign_add'
 GitSignsChange = 'sign_change'
 GitSignsDelete = 'sign_delete'

[LSP]
 LspDiagnosticsDefaultError = 'error_red'
 LspDiagnosticsDefaultWarning = 'warning_orange'
 LspDiagnosticsDefaultInformation = 'info_yellow'
 LspDiagnosticsDefaultInfo = 'info_yellow'
 LspDiagnosticsDefaultHint = 'hint_blue'
 LspDiagnosticsVirtualTextError = 'error_red'
 LspDiagnosticsVirtualTextWarning = 'warning_orange'
 LspDiagnosticsVirtualTextInformation = 'info_yellow'
 LspDiagnosticsVirtualTextInfo = 'info_yellow'
 LspDiagnosticsVirtualTextHint = 'hint_blue'
 LspDiagnosticsFloatingError = 'error_red'
 LspDiagnosticsFloatingWarning = 'warning_orange'
 LspDiagnosticsFloatingInformation = 'info_yellow'
 LspDiagnosticsFloatingInfo = 'info_yellow'
 LspDiagnosticsFloatingHint = 'hint_blue'
 DiagnosticSignError = 'error_red'
 DiagnosticSignWarning = 'warning_orange'
 DiagnosticSignInformation = 'info_yellow'
 DiagnosticSignInfo = 'info_yellow'
 DiagnosticSignHint = 'hint_blue'
 LspDiagnosticsSignError = 'error_red'
 LspDiagnosticsSignWarning = 'warning_orange'
 LspDiagnosticsSignInformation = 'info_yellow'
 LspDiagnosticsSignInfo = 'info_yellow'
 LspDiagnosticsSignHint = 'hint_blue'
 LspDiagnosticsError = 'error_red'
 LspDiagnosticsWarning = 'warning_orange'
 LspDiagnosticsInformation = 'info_yellow'
 LspDiagnosticsInfo = 'info_yellow'
 LspDiagnosticsHint = 'hint_blue'
 LspDiagnosticsUnderlineError = 'error_red - u'
 LspDiagnosticsUnderlineWarning = 'warning_orange - u'
 LspDiagnosticsUnderlineInformation = 'info_yellow - u'
 LspDiagnosticsUnderlineInfo = 'info_yellow - u'
 LspDiagnosticsUnderlineHint = 'hint_blue - u'
 LspReferenceRead = '- blue_bg'
 LspReferenceText = '- blue_bg'
 LspReferenceWrite = '- blue_bg'
 LspCodeLens = 'comment - i'
 LspCodeLensSeparator = 'white - i'

[StatusLine]
 StatusLine = 'gray_light dark'
 StatusLineNC = 'gray dark'
 StatusLineSeparator = 'bg'
 StatusLineTerm = 'gray'
 StatusLineTermNC = 'gray'

[Telescope]
 TelescopeSelection = 'dark blue'
 TelescopeMatching = 'white - b'
 TelescopeBorder = 'blue bg'

[IndentBlankline]
 IndentBlanklineContextChar = 'magenta'
 IndentBlanklineContextStart = '- - u'
 IndentBlanklineChar = 'gray'
 IndentBlanklineSpaceChar = 'cyan'
 IndentBlanklineSpaceCharBlankline = 'yellow'

[Illuminate]
 illuminateCurWord = 'link:IncSearch'
 illuminateWord = 'link:IncSearch'

[Notify]
 NotifyERRORBorder = 'error_red'
 NotifyERRORIcon = 'error_red'
 NotifyERRORTitle  = 'error_red'
 NotifyWARNBorder = 'warning_orange'
 NotifyWARNIcon = 'warning_orange'
 NotifyWARNTitle = 'warning_orange'
 NotifyDEBUGBorder = 'gray'
 NotifyDEBUGIcon = 'gray'
 NotifyDEBUGTitle  = 'gray'
 NotifyTRACEBorder = 'purple'
 NotifyTRACEIcon = 'purple'
 NotifyTRACETitle  = 'purple'
 NotifyINFOBorder = 'hint_blue'
 NotifyINFOIcon = 'hint_blue'
 NotifyINFOTitle = 'hint_blue'
 NotifyERRORBody = 'link:Normal'
 NotifyWARNBody = 'link:Normal'
 NotifyINFOBody = 'link:Normal'
 NotifyDEBUGBody = 'link:Normal'
 NotifyTRACEBody = 'link:Normal'
 NotifyBackground = '- dark'

[Syntax]
 tsxIntrinsicTagName = 'magenta'
 tsxAttrib = 'white'
 tsxString = 'blue'

[Noice]
 NoiceCmdlinePopupBorder = 'white'
